/*Generated by SharpKit v4.29.7000*/
if(typeof(Alterity) == "undefined")
    Alterity = {};
if(typeof(Alterity.Models) == "undefined")
    Alterity.Models = {};

Alterity.Models.IntegerInterval = function(left,length)
{
    this.Left = left;
    this.Length = length;
};

Object.defineProperty(Alterity.Models.IntegerInterval.prototype, "right", {
    get: function () {
        return this.Left + this.Length - 1;
    },
    set: function (value) {
        this.Length = value - this.Left + 1;
    }
});

Alterity.Models.IntegerInterval.prototype.InsertTransformSelection = function (Tranformer)
{
    if(Tranformer.Left <= this.Left)
    {
        return [new Alterity.Models.IntegerInterval(this.Left + Tranformer.Length,this.Length)];
    }
    else if(Tranformer.Left < this.Left + this.Length)
    {
        return [new Alterity.Models.IntegerInterval(this.Left,Tranformer.Left - this.Left),new Alterity.Models.IntegerInterval(Tranformer.Left + Tranformer.Length,this.Length - (Tranformer.Left - this.Left))];
    }
    else
    {
        return [this];
    }
};
Alterity.Models.IntegerInterval.prototype.DeleteTransformSelection = function(asInsertion)
{
    var leftShiftCount=Math.max(0,Math.min(this.Left - asInsertion.Left,asInsertion.Length));
    var upperBoundMin=Math.min(this.Left + this.Length - 1,asInsertion.Left + asInsertion.Length - 1);
    var lowerBoundMax=Math.max(this.Left,asInsertion.Left);
    var lengthReduction=(lowerBoundMax <= upperBoundMin)?Math.max(upperBoundMin - lowerBoundMax + 1,0):0;
    var newLength=this.Length - lengthReduction;
    if(newLength > 0)
    {
        return [new Alterity.Models.IntegerInterval(this.Left - leftShiftCount,newLength)];
    }
    else
    {
        return [];
    }
};
Alterity.Models.IntegerInterval.prototype.InsertTransformInsertion = function(asInsertion)
{
    if(asInsertion.Left <= this.Left)
    {
        return [new Alterity.Models.IntegerInterval(this.Left + asInsertion.Length,this.Length)];
    }
    else
    {
        return [this];
    }
};
Alterity.Models.IntegerInterval.prototype.DeleteTransformInsertion = function(asDeletion)
{
    var leftShift=Math.max(0,Math.min(this.Left - asDeletion.Left,asDeletion.Length));
    return [new Alterity.Models.IntegerInterval(this.Left - leftShift,this.Length)];
};
Alterity.Models.IntegerInterval.prototype.InsertTransformInsertionSwappedPrecedence = function(asInsertion)
{
    if(asInsertion.Left < this.Left)
    {
        return [new Alterity.Models.IntegerInterval(this.Left + asInsertion.Length,this.Length)];
    }
    else
    {
        return [this];
    }
};
Alterity.Models.IntegerInterval.prototype.Intersection = function(other)
{
    var result=new Alterity.Models.IntegerInterval();
    if(other.Right >= this.Left && other.Left <= this.Right)
    {
        result.Left = Math.max(other.Left,this.Left);
        result.Length = Math.min(other.Right,this.Right) - result.Left + 1;
    }
    else
    {
        result.Left = 0;
        result.Length = 0;
    }
    return result;
};
Alterity.Models.IntegerInterval.prototype.Union = function(other)
{
    var result=new Alterity.Models.IntegerInterval();
    if(other.Right >= this.Left && other.Left <= this.Right)
    {
        result.Left = Math.min(other.Left,this.Left);
        result.Length = Math.max(other.Right,this.Right) - result.Left + 1;
    }
    else
    {
        result.Left = 0;
        result.Length = 0;
    }
    return result;
};
Alterity.Models.IntegerInterval.prototype.Subtract = function(other)
{
    if(other.Right >= this.Left && other.Left <= this.Right)
    {
        var leftResultLength=Math.max(other.Left - this.Left,0);
        var rightResultLength=Math.max(this.Right - other.Right,0);
        if(leftResultLength + rightResultLength < this.Length)
        {
            if(leftResultLength > 0)
            {
                if(rightResultLength > 0)
                {
                    return [new Alterity.Models.IntegerInterval(this.Left,leftResultLength),new Alterity.Models.IntegerInterval(this.Right - rightResultLength + 1,rightResultLength)];
                }
                else
                {
                    return [new Alterity.Models.IntegerInterval(this.Left,leftResultLength)];
                }
            }
            else
            {
                if(rightResultLength > 0)
                {
                    return [new Alterity.Models.IntegerInterval(this.Right - rightResultLength + 1,rightResultLength)];
                }
                else
                {
                    return [];
                }
            }
        }
    }
    return [this];
};
